version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  
  pre_build:
    commands:
      - echo log in to Amazon ECR...
      - pip install --upgrade pip
      - pip install --upgrade awscli==1.18.17
     # - apk update && apk add --no-cache aws-cli
     # - aws s3 ls
      - aws --version
      - echo us-west-2
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 883013188679.dkr.ecr.us-west-2.amazonaws.com
      - REPOSITORY_URI=883013188679.dkr.ecr.us-west-2.amazonaws.com/aws-ecs-1
      #- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 883013188679.dkr.ecr.us-west-2.amazonaws.com
      #- REPOSITORY_URI=883013188679.dkr.ecr.us-west-2.amazonaws.com/aws-ecs
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image.
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo write definitions file...
      - printf '[{"name":"demo-node","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
